name: Go

on:
  push:
    branches: [ master ]
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.19", "1.20"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Cover
      run: |      
        go test -race -coverprofile=cover.out -coverpkg=./... -v ./...
        go tool cover -html=cover.out -o cover.html

    - name: Upload coverage to codecov.io
      uses: codecov/codecov-action@v1
